### ISSUE TITLE
Check python version on the destination host and update if needed

### ISSUE THREAD

**Issue by ricardom-splunk** [ricardom-splunk/soar_installer_ansible#7]
Sometimes the destination machine comes with older python versions (default for CentOS7 could be as old as Python 2.7)

If possible, Ansible should detect that and try to install a newer support Python version

**Comment by pdros-splunk** [comment]
If there is no Python3 installed on a machine, the ansible script will install python3.6.8

**Comment by ricardom-splunk** [comment]
1. After yesterday we discovered that SOAR 6 brings python 3.9 included, is this still needed?
1.1 Does SOAR 5.x bring python too?
(yes, I know it's partly because of passlib but maybe there's other solutions?)

2. Why aren't we trying to aim for some newer version than 3.6.8 ?

**Comment by pdros-splunk** [comment]
1. If there will be just python2 without installing pip3 and python3, there will be an error on installing passlib and setting the same password as provided in vars file, then installing script will automatically update python to 3.9
